import { Router } from "express";
import { register, login, me } from "../controllers/authController.js";
import { validate } from "../middleware/validationMiddleware.js";
import { requireAuth } from "../middleware/authMiddleware.js";
import { registerSchema, loginSchema } from "../validators/authValidators.js";
const router = Router();
router.post("/register", validate(registerSchema), register);
router.post("/login", validate(loginSchema), login);
router.get("/me", requireAuth, me);
export default router;
